# Generated by Django 5.1.7 on 2025-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('contacts', models.JSONField(default=dict)),
                ('activity_themes', models.JSONField(default=list)),
            ],
        ),
    ]
