# Generated by Django 5.1.7 on 2025-04-28 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contacts',
        ),
        migrations.AddField(
            model_name='company',
            name='additional_contacts',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные контактные данные в формате JSON', verbose_name='Доп. контакты'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='activity_themes',
            field=models.JSONField(blank=True, default=list, help_text='Список видов деятельности', verbose_name='Виды деятельности'),
        ),
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Приоритет'),
        ),
    ]
