# Generated by Django 5.1.7 on 2025-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_company_contacts_company_additional_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название вида деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='activity_themes',
        ),
        migrations.AlterField(
            model_name='company',
            name='additional_contacts',
            field=models.TextField(blank=True, help_text='Формат: Тип:значение (например, Telegram:@example)', verbose_name='Доп. контакты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург'), ('Новосибирск', 'Новосибирск'), ('Екатеринбург', 'Екатеринбург'), ('Казань', 'Казань'), ('Нижний Новгород', 'Нижний Новгород'), ('Челябинск', 'Челябинск'), ('Самара', 'Самара')], max_length=100, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='company',
            name='activity_themes',
            field=models.ManyToManyField(blank=True, to='newapp.activitytheme', verbose_name='Виды деятельности'),
        ),
    ]
