# Generated by Django 5.1.7 on 2025-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_company_phone_company_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytheme',
            options={'ordering': ['name'], 'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
        migrations.AlterField(
            model_name='company',
            name='additional_contacts',
            field=models.TextField(blank=True, help_text='Формат: Тип:значение (например, Telegram:@example)', verbose_name='Доп. сведения'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('Россия', 'Россия'), ('Франция', 'Франция'), ('Германия', 'Германия'), ('США', 'США'), ('Китай', 'Китай'), ('Япония', 'Япония'), ('Великобритания', 'Великобритания'), ('Италия', 'Италия'), ('Испания', 'Испания'), ('Канада', 'Канада')], max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Краткое название'),
        ),
    ]
